site_name: "MS Order - Documentation"
site_description: "All about MS Order API and related components"

nav:
  - Overview: 
      - What is Order Microservice?: 'overview/what-is-ms-order.md'
      - Service architecture: 'overview/ms-architecture.md'
      - Features:
          - External Order:
              - Partners: 'features/partners.md'
plugins:
  - techdocs-core
